### ISSUE TITLE
Abstand zwischen Nummerierung und Überschrift zu klein

### ISSUE THREAD

**Issue by mgmax** [UBEN-Webteam/FAU-University-Press-LaTeX-Formatvorlage#6]
Die Vorlage nutzt derzeit eine feste Einrückung (`\@fausectioning`) der Überschriften, unabhängig von der Länge der Nummerierung:

![Screenshot Bild 2](https://user-images.githubusercontent.com/1520891/124349921-eb869880-dbf1-11eb-8275-2defbf2259c4.png)

![Screenshot BIld](https://user-images.githubusercontent.com/1520891/124349844-a5c9d000-dbf1-11eb-8d42-67fb9306db38.png)

Dadurch ist bei sub-sub-sections nicht genug Platz für die Nummerierung. Im obigen Beispiel ist es schon knapp, und je nach Zahl überlappen sogar die Nummerierung und Überschrift (z.B. "5.5.5.5" ist besonders breit, "1.1.1.1" dagegen schmal genug).

Welche Lösung wird empfohlen?

- Keine feste Einrückung
- Pauschal mehr einrücken, sodass auch für "5.5.5.5." genug Platz ist

**Comment by fau-university-press** [comment]
Wir werden bei \newcommand*{\@fausectioning}[1]{\makebox[1.1cm][l]{#1}} auf 1.3cm erhöhen.
